FROM python:3

RUN pip install virtualenv

WORKDIR /src

# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt
# COPY requirements-dev.txt ./
# RUN pip install --no-cache-dir -r requirements-dev.txt
# COPY . .
