version: 2
jobs:
  backend: # job name
    docker: # Specifies the primary container image,
    # see circleci.com/docs/2.0/circleci-images/ for
    # the list of pre-built CircleCI images on dockerhub.
      - image: circleci/python:3.7.12
        environment:
          SQLALCHEMY_TEST_DATABASE_URI: 'postgresql://testuser:testpw@localhost:5432/forumtest'

      - image: postgres:9.6.11 # Specifies the database image
       # for the secondary or service container run in a common
       # network where ports exposed on the primary container are
       # available on localhost.
        environment: # Specifies the POSTGRES_USER authentication
         # environment variable, see circleci.com/docs/2.0/env-vars/
         # for instructions about using environment variables.
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpw
          POSTGRES_DB: forumtest

    steps:
      - checkout
      - run: cd backend && pip install --user -r requirements.txt
      - run: cd backend && pip install --user -r requirements-dev.txt
      - run: cd backend && python -m mypy  --install-types --non-interactive .
      - run: cd backend && python -m flake8 .
      - run: cd backend && python -m pytest --cov app --cov-report=html
      - store_artifacts:
          path: backend/htmlcov

  frontend: # job name
    docker:
      - image: circleci/node:10.16.0
    parallelism: 1
    working_directory: ~/app
    steps:
      - checkout
      - run: cd frontend && yarn install
      - run: cd frontend && yarn prettier-check
      - run: cd frontend && yarn lint
      - run: cd frontend && yarn test:unit-coverage
      - store_artifacts:
          path: frontend/coverage

workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - backend
      - frontend
